services:
  mysql-ecommerce-app-container:
    image: mysql:8.0.36-bullseye
    container_name: mysql-ecommerce-app-container
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config-deamond:/etc/mysql/conf.d
    environment:
      MYSQL_USER: tranvandat
      MYSQL_PASSWORD: tranvandat12@
      MYSQL_ROOT_PASSWORD: tranvandat12@
      MYSQL_DATABASE: ecommerce_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
#    networks:
#      - ecommerce-app-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: springboot-ecommerce-app
#    depends_on:
#      mysql-ecommerce-app-container:
#        condition: service_healthy
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-ecommerce-app-container:3306/ecommerce_app?allowPublicKeyRetrieval=true&useSSL=false
#      MYSQL_USERNAME: tranvandat
#      MYSQL_ROOT_PASSWORD: tranvandat12@
#    networks:
#      - ecommerce-app-network

volumes:
  mysql-data:
  mysql-config-deamond:

networks:
  ecommerce-app-network:
    name: ecommerce-app-network
    driver: bridge