server:
  port: 8088
  servlet:
    context-path: /ecommerce

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_app?&createDatabaseIfNotExist=True&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1

jwt:
  expiration:
  secretKey:

aws:
  s3:
    bucket-name:
    region:
    access-key-id:
    secret-access-key:

