server:
  port: 8088
  servlet:
    context-path: /ecommerce

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce_app?&createDatabaseIfNotExist=True&serverTimezone=UTC}
    username: tranvandat
    password: ${MYSQL_ROOT_PASSWORD:tranvandat12@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      #spring.data.redis.use-redis-cache
      use-redis-cache: false
      host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
      #host: ${REDIS_HOST:ubuntu-server-01.local} # Default to 'localhost' if not provided
      port: ${REDIS_PORT:6379}      # Default to 6379 if not provided

api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: 8xrvlDKv5PS/jLEtbKxgmjM6kJcSLNkG+rn9TY1bLmmVpAe04eiudmRrEsiKNF62

aws:
  s3:
    bucket-name:
    region:
    access-key-id:
    secret-access-key:

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"